apiVersion: aws.platform.upbound.io/v1alpha1
kind: XEKS
metadata:
  name: configuration-aws-assume-gcp
spec:
  parameters:
    id: configuration-aws-assume-gcp
    region: us-west-2
    version: "1.27"
    iam:
      roleArn: arn:aws:iam::12345678910:role/AWSReservedSSO_AdministratorAccess_d703c73ed340fde7
    nodes:
      count: 3
      instanceType: t3.small
    gcp:
      projectName: crossplane-playground
      projectId: "12345678910"
      workloadIdentityPoolName: configuration-aws-assume-gcp
      serviceAccountName: configuration-aws-assume-gcp
  writeConnectionSecretToRef:
    name: configuration-aws-assume-gcp-kubeconfig
    namespace: upbound-system
